[package]
name = "rustygit"
version = "0.1.0"
authors = ["Keir Lawson <keirlawson@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
thiserror = "1"

[badges]
travis-ci = { repository = "keirlawson/rusty-git" }